The list of required the ingredients:
FOR THE CAKE:
Nonstick vegetable oil cooking spray
3/4 c. butter
3 Large eggs
1/2 c. Sour cream
2 tsp. pure vanilla extract
2 c. all=purpose flour
1 1/2 c. granulated sugar
1/2 c. packed dark brown sugar
3/4 Unsweetened cocoa powder
1 1/2 tsp. baking soda
1 tsp. baking powder
1 tsp. kosher salt
FOR THE FROSTING:
1 1/2 c. bittersweetor semisweet chocolate chips
1 c. heavy cream